name: Build and Publish image to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:

  build-main:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build ./apps/main -t bkirillv/main:latest
      - name: Push the Docker image
        run: |
          docker push bkirillv/main:latest
